

import '../globals.css'
import '../index.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ToasterProvider from '../providers/ToasterProvider'
import Protect from './Protect'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}><ToasterProvider /><Protect>{children}</Protect></body>
    </html>
  )
}
